### ISSUE TITLE
Städte-Dropdown lädt Daten nicht nach (API)

### ISSUE THREAD

**Issue by winkelement** [neuemedienmacher/hbgl-admin#2]
Beim hinzufügen von Städten (city) werden nicht alle DAten geladen:
<img width="717" alt="Screenshot 2022-01-28 at 14 34 57" src="https://user-images.githubusercontent.com/3525191/151556144-c0c5ae4a-a294-43d7-b9b4-0c84bc1db0b6.png">

**Comment by andirotter** [comment]
fixed in #3
